spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/mydb
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logs utiles pour voir les DDL/SQL au démarrage
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.tool.hbm2ddl=debug

server.port=9999

# ===========================
#  Internationalization (i18n)
# ===========================

# Encodage UTF?8 pour tous les fichiers de messages
spring.messages.encoding=UTF-8
spring.messages.basename=messages
spring.messages.fallback-to-system-locale=false

# Chemin du fichier de log
logging.file.name=logs/app.log

# Taille max avant rotation
logging.logback.rollingpolicy.max-file-size=10MB

# Nombre de fichiers archivés conservés
logging.logback.rollingpolicy.max-history=30

# Niveau de log (optionnel)
logging.level.root=INFO
logging.level.com.tonpackage=DEBUG